application: helloworld
version: 1
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/channel/connected/
  script: _go_app

- url: /_ah/channel/disconnected/
  script: _go_app

- url: /.*
  script: _go_app
  login: required
